"""empty message

Revision ID: 203352412ef1
Revises: 9a6e34cc105
Create Date: 2014-06-19 16:35:27.759529

"""

# revision identifiers, used by Alembic.
revision = '203352412ef1'
down_revision = '9a6e34cc105'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
