"""empty message

Revision ID: 2d9127d3ff40
Revises: 34e7cc4bea
Create Date: 2014-06-19 15:57:54.628035

"""

# revision identifiers, used by Alembic.
revision = '2d9127d3ff40'
down_revision = '34e7cc4bea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
