"""empty message

Revision ID: 493ea8558565
Revises: None
Create Date: 2014-06-16 20:59:46.453574

"""

# revision identifiers, used by Alembic.
revision = '493ea8558565'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
