"""empty message

Revision ID: 5086e1dd760b
Revises: be19e75d7bd
Create Date: 2014-06-20 00:03:20.078744

"""

# revision identifiers, used by Alembic.
revision = '5086e1dd760b'
down_revision = 'be19e75d7bd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
