"""empty message

Revision ID: 9a6e34cc105
Revises: 2d9127d3ff40
Create Date: 2014-06-19 16:15:16.337363

"""

# revision identifiers, used by Alembic.
revision = '9a6e34cc105'
down_revision = '2d9127d3ff40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
