"""empty message

Revision ID: be19e75d7bd
Revises: 203352412ef1
Create Date: 2014-06-20 00:02:23.111734

"""

# revision identifiers, used by Alembic.
revision = 'be19e75d7bd'
down_revision = '203352412ef1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
